SEED_RULES = [
    (
        "sql-core-01",
        "OWASP SQLi Core Ruleset",
        # Layered SQLi — matches attack fragments only, not benign English.
        # Each alternative is a real SQLi vector: UNION, stacked queries, tautologies,
        # time-based, OOB exfil, hex literals, comment terminators, schema enumeration.
        r"(?i)((?:union\s+(?:all\s+)?select\b)|(?:;\s*(?:drop|truncate|delete|update|insert|alter|create|exec(?:ute)?|grant|revoke)\b)|(?:'\s*(?:or|and)\s*'?\w*'\s*=\s*'?\w*)|(?:\bor\b\s+\d+\s*=\s*\d+)|(?:\band\b\s+\d+\s*=\s*\d+)|(?:--\s*$|;--)|(?:/\*![\s\S]*?\*/)|(?:\bwaitfor\s+delay\s+')|(?:benchmark\s*\(\s*\d{2,}\s*,\s*md5)|(?:pg_sleep\s*\(\s*\d+\s*\))|(?:0x[0-9a-f]{8,})|(?:load_file\s*\()|(?:into\s+(?:out|dump)file\s+['\"])|(?:information_schema\.)|(?:xp_(?:cmdshell|dirtree|regread|regwrite|terminate))\b|(?:\bexec(?:ute)?\s*[\(\w])|(?:char\s*\(\s*\d+\s*\)\s*\+)|(?:db_name\s*\(\s*\))|(?:user\s*\(\s*\))|(?:version\s*\(\s*\))|(?:\bcurrent_user\b))",
        "Drop & Blacklist",
        "SQLi",
        1,
        1420,
        "Level 1",
        "Layered SQLi detection. Combines context-aware attack fragments (UNION SELECT, stacked queries, tautologies, time-based, OOB exfil, hex literals, conditional comments, schema enumeration) to avoid matching benign SELECT in any context.",
    ),
    (
        "xss-scrutiny-01",
        "XSS Aggressive Scrutiny",
        r"(<script.*?>[\s\S]*?<\/script>)|(javascript\s*:\s*\S+)|(on\w+\s*=\s*['\"].*?['\"])|(<\s*iframe.*?>)",
        "Drop & Blacklist",
        "XSS",
        1,
        92,
        "Level 3",
        "High-sensitivity detection for cross-site scripting in JSON payloads and GraphQL endpoints.",
    ),
    (
        "bot-blocker-01",
        "Bad Bot Blocker [Legacy]",
        r"(curl|wget|python-requests|scrapy|nikto|sqlmap|nmap)",
        "Log Payload Only",
        "DEPRECATED",
        0,
        0,
        "DEPRECATED",
        "Simple user-agent based bot blocking. Superseded by AEGIS AI-Fingerprinting.",
    ),
    (
        "rfi-blocker-01",
        "Remote File Inclusion (RFI)",
        r"(https?|ftp|file|php|data):\/",
        "Drop & Blacklist",
        "CRITICAL",
        1,
        12,
        "CRITICAL",
        "Blocks attempts to include remote files via URI schemes in parameter fields.",
    ),
    (
        "cmd-injection-01",
        "Command Injection Shield",
        r"(;|\||`|\$\(|&&|\|\|)\s*(cat|ls|pwd|whoami|id|uname|wget|curl|bash|sh|nc|netcat|python|perl|ruby|php)\b",
        "Drop & Blacklist",
        "CMDi",
        1,
        0,
        "CRITICAL",
        "Detects OS command injection attempts via shell metacharacters and common binaries.",
    ),
    (
        "path-traversal-01",
        "Path Traversal Protection",
        r"(\.\.\/|\.\.\\|%2e%2e%2f|%2e%2e\/|\.\.%2f|%2e%2e%5c)",
        "Drop & Blacklist",
        "PATH",
        1,
        0,
        "Level 2",
        "Prevents directory traversal attacks targeting sensitive file access.",
    ),
    (
        "lfi-rfi-01",
        "Local/Remote File Inclusion",
        r"(php://|file://|expect://|zip://|zlib://|data://|glob://|phar://)",
        "Drop & Blacklist",
        "LFI",
        1,
        0,
        "CRITICAL",
        "Blocks PHP wrapper injection and file inclusion vector attacks.",
    ),
    (
        "xml-xxe-01",
        "XML External Entity (XXE)",
        r"(<!ENTITY|SYSTEM|PUBLIC)\s+.*?(file|expect|http|https|ftp)",
        "Drop & Blacklist",
        "XXE",
        1,
        0,
        "CRITICAL",
        "Prevents XML External Entity attacks that can read local files or SSRF.",
    ),
    (
        "ssti-01",
        "Server-Side Template Injection",
        r"(\{\{.*\}\}|\{\%.*\s*(import|include|extends)\s*\%\}|#\{.*\}|\$\{.*\}|jsp:.*|asp:.*)",
        "Drop & Blacklist",
        "SSTI",
        1,
        0,
        "CRITICAL",
        "Detects template injection attacks in Jinja2, Twig, Velocity, and other template engines.",
    ),
    (
        "jsonp-abuse-01",
        "JSONP Callback Abuse",
        r"callback\s*=\s*['\"]?\s*[a-zA-Z0-9_$]+\s*['\"]?",
        "Log Payload Only",
        "JSONP",
        1,
        0,
        "Level 3",
        "Flags potential JSONP abuse and cross-origin data exfiltration attempts.",
    ),
]
