apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kalki-waf.name" . }}-config
  labels:
    {{- include "kalki-waf.labels" . | nindent 4 }}
data:
  blocked-countries: "{{ join "," .Values.config.blockedCountries }}"
  trusted-ips: "{{ join "," .Values.config.trustedIPs }}"
  cors-origins: "{{ join "," .Values.config.corsOrigins }}"
