apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kalki-waf.name" . }}-secrets
  labels:
    {{- include "kalki-waf.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  js-challenge-secret: {{ .Values.secrets.jsChallengeSecret | b64enc | quote }}
  csrf-secret: {{ .Values.secrets.csrfSecret | b64enc | quote }}
  firebase-credentials: {{ .Values.secrets.firebaseCredentials | b64enc | quote }}
